---
- hosts: raspi
  tasks:
    - setup:
  remote_user: root
  gather_facts: no

- hosts: webservers
  roles:
      - sfpg
  remote_user: root

- hosts: raspi
  roles:
      - dochang.pip
      - raspicam
      - raspicam-offsite-image-copy
  remote_user: root
