---
- hosts: raspi
  vars:
    - raspi_initial_setup_first_time_run: False
  roles:
    - raspi_initial_setup
  remote_user: root
  gather_facts: no

- hosts: webservers
  roles:
    - sfpg
  remote_user: root

- hosts: raspi
  roles:
    - dochang.pip
    - distribute-ssh-keys
    - raspicam
    - raspicam-offsite-image-copy
  remote_user: root
