---
- hosts: raspi
  vars:
    raspicam_offsite_image_copy_ssh_login: root
    raspicam_offsite_image_copy_server_name: lkcm.eu
    raspicam_offsite_image_copy_enable_ftp: True
    raspicam_offsite_image_copy_ftp_ip: 192.168.1.1
    raspicam_name: test
  roles:
      - dochang.pip
      - raspicam
      - sfpg
      - raspicam-offsite-image-copy
