---
- hosts: ogn
  user: root
  become: yes
  roles:
    - ansible-role-enable-root-pubkey-login
    - ansible-role-ogn-node
#    - ansible-role-mobile-net-setup

- hosts: servers
  remote_user: root
  roles:
    - ansible-role-get-hostname
    - ansible-role-openvpn

- hosts: ogn
  user: root
  become: yes
  roles:
    - ansible-role-copy-client-certs
