---
- hosts: ogn
  user: root
  become: yes
  roles:
    - ansible-role-enable-root-pubkey-login
    - ansible-role-mobile-net-setup
    - ansible-role-ogn-node

- hosts: lkcm-eu
  remote_user: root
  roles:
    - ansible-role-get-hostname
    - ansible-role-openvpn

- hosts: ogn
  user: root
  become: yes
  roles:
    - ansible-role-copy-client-certs
